const rooms = {
    '62': {
        'address': 'Kalman Gavrielov 39',
        'favicon': 'https://static.wixstatic.com/media/26fd72_cbacc003aadb4347835e84c4e1dd3f3b.png/v1/fit/w_467,h_420,usm_0.66_1.00_0.01/26fd72_cbacc003aadb4347835e84c4e1dd3f3b.png',
        'roomescape_id': 'the-submarine',
        'name': 'The Submarine',
        'tel': '053-2241594',
        'y': 34.7843978,
        'people': '2-5',
        'trip': '',
        'city': 'Rehovot',
        'x': 31.8882041,
        'id': 62,
        'facebook': 'https://www.facebook.com/Escape-Room-Rehovot-1078136592231363/',
        'escapecard': '1',
        'company': 'Golden Key',
        'selected': true,
        'link': 'http://www.mygoldenkey.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank/tf84k',
        'review_score': '4.9'
    },
    '23': {
        'address': 'Hatmarim Blvd.',
        'favicon': 'https://static.wixstatic.com/media/b89899_52a8a0d777604b0abb188054d10ed8ab.jpg/v1/fill/w_104,h_90,al_c,q_75,usm_0.50_1.20_0.00/b89899_52a8a0d777604b0abb188054d10ed8ab.jpg',
        'roomescape_id': 'alcatraz',
        'name': 'Alcatraz',
        'tel': '053-2552515',
        'y': 34.9510095,
        'people': '2-3',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293980-d7901185-Reviews-Run_Out-Eilat_Southern_District.html',
        'city': 'Eilat',
        'x': 29.5610439,
        'id': 23,
        'facebook': 'https://www.facebook.com/RunOut.EscapeGame',
        'escapecard': '1',
        'company': 'Run Out',
        'selected': true,
        'link': 'http://www.run-out.net/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!alcatraz/c1a91',
        'review_score': '8.1'
    },
    '110': {
        'address': 'Hahistadrut 37',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'dungeon',
        'name': 'Dungeon',
        'tel': '052-7213166',
        'y': 34.7887911,
        'people': '2-4',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Beer Sheva',
        'x': 31.2395643,
        'id': 110,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://exitroom.co.il/rooms/dungeon?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '6.7'
    },
    '37': {
        'address': 'Metsudat Betar 8',
        'favicon': '',
        'roomescape_id': 'horrors-of-trenton',
        'name': 'Horrors of Trenton',
        'tel': '03-6095110',
        'y': 34.7504926,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g297740-d8870171-Reviews-RSQ_Real_Story_Quest-Bat_Yam_Tel_Aviv_District.html',
        'city': 'Bat Yam',
        'x': 32.0133216,
        'id': 37,
        'facebook': 'https://www.facebook.com/rsqisrael/',
        'escapecard': '',
        'company': 'RSQ - Real Story Quest',
        'selected': true,
        'link': 'http://rsqisrael.com/heb/Booking/room1?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.7'
    },
    '100': {
        'address': 'Ha-Bonim 4',
        'favicon': '/static/Logos/escapeout.png',
        'roomescape_id': 'run-from-venice',
        'name': 'Escape From Venice',
        'tel': '054-6581297',
        'y': 34.9031169,
        'people': '2-6',
        'trip': '',
        'city': 'Netanya',
        'x': 32.3175952,
        'id': 100,
        'facebook': 'https://www.facebook.com/escapeout/',
        'escapecard': '1',
        'company': 'Escape Out',
        'selected': true,
        'link': 'http://www.escapeout.co.il/escape-from-venice?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.2'
    },
    '118': {
        'address': 'Sokolov 42',
        'favicon': '/static/Logos/5d.png',
        'roomescape_id': 'the-hell',
        'name': 'The Hell',
        'tel': '050-5078701',
        'y': 34.77360609999999,
        'people': '2-6',
        'trip': '',
        'city': 'Holon',
        'x': 32.0227643,
        'id': 118,
        'facebook': 'https://www.facebook.com/5DRealitygame/',
        'escapecard': '',
        'company': '5D Reality Game',
        'selected': true,
        'link': 'http://reality-game.co.il/?page_id=43&utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.1'
    },
    '63': {
        'address': 'David Saharov 10',
        'favicon': '',
        'roomescape_id': 'i-am-legend',
        'name': 'I am Legend',
        'tel': '077-3610000',
        'y': 34.7692168,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7928499-Reviews-Brainit_Real_Life_Room_Escape_Game-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Rishon LeZion',
        'x': 31.9918669,
        'id': 63,
        'facebook': 'https://www.facebook.com/brainit.co.il',
        'escapecard': '',
        'company': 'Brainit',
        'selected': true,
        'link': 'http://brainit.co.il/game/i-am-legend/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.7'
    },
    '61': {
        'address': 'Etsel 6',
        'favicon': '/static/Logos/escaperoom.png',
        'roomescape_id': 'prison-break',
        'name': 'Prison Break',
        'tel': '03-6120879',
        'y': 34.7674141,
        'people': '2-8',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7351270-Reviews-Escape_Room_Israel-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Rishon LeZion',
        'x': 31.988429,
        'id': 61,
        'facebook': 'https://www.facebook.com/escaperoom.israel',
        'escapecard': '',
        'company': 'Escaperoom',
        'selected': true,
        'link': 'http://www.escaperoom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!escape-room-rishon-hebrew/vbief',
        'review_score': '8.9'
    },
    '1': {
        'address': 'Abulafiya 25',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'maniacs-shelter',
        'name': "Maniac's Shelter",
        'tel': '054-9557666',
        'y': 34.7695098,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0520306,
        'id': 1,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://www.exitroom.co.il/rooms/maniacs-shelter/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.6'
    },
    '26': {
        'address': 'Yokhanan ha-Sandlar 13',
        'favicon': '',
        'roomescape_id': 'real-detective',
        'name': 'Real Detective',
        'tel': '04-6328767',
        'y': 35.0400453,
        'people': '2-4',
        'trip': '',
        'city': 'Haifa',
        'x': 32.7901375,
        'id': 26,
        'facebook': 'https://www.facebook.com/QuestRoom.Israel',
        'escapecard': '',
        'company': 'Quest Room',
        'selected': true,
        'link': 'http://www.questroom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!quest-room/ctz7',
        'review_score': '8.8'
    },
    '5': {
        'address': 'Allenby 65',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'capital-punishment',
        'name': 'Capital Punishment',
        'tel': '053-5224340',
        'y': 34.7710173,
        'people': '2-3',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0681333,
        'id': 5,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://www.exitroom.co.il/rooms/capital_punishment/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.6'
    },
    '65': {
        'address': 'Sderot HaNassi 104',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'the-ring',
        'name': 'The Ring',
        'tel': '053-5318227',
        'y': 34.986252,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Haifa',
        'x': 32.8078284,
        'id': 65,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://exitroom.co.il/rooms/the-ring?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.2'
    },
    '108': {
        'address': 'Ha-Yarkon 167',
        'favicon': '',
        'roomescape_id': 'haunted-castle',
        'name': 'Haunted Castle',
        'tel': '052-4382850',
        'y': 34.7702308,
        'people': '2-6',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0856517,
        'id': 108,
        'facebook': '',
        'escapecard': '',
        'company': 'Nightmare',
        'selected': true,
        'link': 'http://www.nightmare-room.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.7'
    },
    '52': {
        'address': 'Ha-Yetsira 13',
        'favicon': '/static/Logos/insideout.png',
        'roomescape_id': 'operation-saffron',
        'name': 'Operation Saffron',
        'tel': '054-2512292',
        'y': 34.8769735,
        'people': '2-6',
        'trip': '',
        'city': 'Raanana',
        'x': 32.1949843,
        'id': 52,
        'facebook': 'https://www.facebook.com/InsideOut-428305137367864/',
        'escapecard': '1',
        'company': 'Inside Out',
        'selected': true,
        'link': 'http://www.insideoutroom.co.il/booking?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.3'
    },
    '73': {
        'address': "Yo'el Moshe Salomon 16",
        'favicon': '',
        'roomescape_id': 'secret-room',
        'name': 'Castle Prisoners',
        'tel': '058-4579797',
        'y': 35.2198788,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293983-d7717662-Reviews-Secret_Room_Jerusalem-Jerusalem_Jerusalem_District.html',
        'city': 'Jerusalem',
        'x': 31.7800299,
        'id': 73,
        'facebook': 'https://www.facebook.com/SecretroomJerusalem',
        'escapecard': '',
        'company': 'Secret Room',
        'selected': true,
        'link': 'http://secretroom.co.il/quests/pobeg-iz-tyurmy/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.4'
    },
    '83': {
        'address': 'Kalman Gavrielov 39',
        'favicon': 'https://static.wixstatic.com/media/26fd72_cbacc003aadb4347835e84c4e1dd3f3b.png/v1/fit/w_467,h_420,usm_0.66_1.00_0.01/26fd72_cbacc003aadb4347835e84c4e1dd3f3b.png',
        'roomescape_id': '',
        'name': 'The Magic Forest ',
        'tel': '053-2241594',
        'y': 34.7843978,
        'people': '4-14',
        'trip': '',
        'city': 'Rehovot',
        'x': 31.8882041,
        'id': 83,
        'facebook': 'https://www.facebook.com/Escape-Room-Rehovot-1078136592231363/',
        'escapecard': '1',
        'company': 'Golden Key',
        'selected': true,
        'link': 'http://www.mygoldenkey.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank/tf84k',
        'review_score': '-'
    },
    '101': {
        'address': 'Derech Menachem Begin 25',
        'favicon': '',
        'roomescape_id': 'walters-secret',
        'name': "Walter's Secret",
        'tel': '054-2809087',
        'y': 34.780418,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d8050752-Reviews-Quest_and_Quest-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0638418,
        'id': 101,
        'facebook': 'https://www.facebook.com/questandquest',
        'escapecard': '1',
        'company': 'Quest & Quest',
        'selected': true,
        'link': 'http://www.escaperoom-quest.co.il/%D7%A1%D7%95%D7%93%D7%95-%D7%A9%D7%9C-%D7%95%D7%95%D7%9C%D7%98%D7%A8/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.3'
    },
    '8': {
        'address': 'Ha-Hashmonaim 100',
        'favicon': '',
        'roomescape_id': 'alice-in-wonderland',
        'name': 'Alice in Wonderland',
        'tel': '03-5531194',
        'y': 34.7868952,
        'people': '2-4',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7917881-Reviews-Questomania-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0692659,
        'id': 8,
        'facebook': 'https://www.facebook.com/questomaniaIsrael',
        'escapecard': '',
        'company': 'Questomania',
        'selected': true,
        'link': 'https://www.questomania.co.il/shop/alice-in-wonderland/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.7'
    },
    '91': {
        'address': 'Kibbutz Amir',
        'favicon': '',
        'roomescape_id': '',
        'name': 'Arecheological Site',
        'tel': '04-6954243',
        'y': 35.6198305,
        'people': '2-5',
        'trip': '',
        'city': 'Galilee',
        'x': 33.17772610000001,
        'id': 91,
        'facebook': 'https://www.facebook.com/galilzone/',
        'escapecard': '',
        'company': 'GalilZone',
        'selected': true,
        'link': 'http://www.galilzone.com/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '-'
    },
    '20': {
        'address': 'HaTikshoret 5',
        'favicon': '/static/Logos/exitgame.png',
        'roomescape_id': 'double-agent',
        'name': 'Double Agent',
        'tel': '058-5595577',
        'y': 34.657145,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g1137841-d7751597-Reviews-ExitGame_Israel-Ashdod_Southern_District.html',
        'city': 'Ashdod',
        'x': 31.813712,
        'id': 20,
        'facebook': 'https://www.facebook.com/exitgame1',
        'escapecard': '1',
        'company': 'Exit Game',
        'selected': true,
        'link': 'http://www.exitgame.co.il/he/Games/Room/3?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.5'
    },
    '71': {
        'address': 'Idelson 7',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'city-s',
        'name': 'Sinner’s City',
        'tel': '058-7063046',
        'y': 34.7678436,
        'people': '4-8',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.074038,
        'id': 71,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://exitroom.co.il/rooms/city-s/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.8'
    },
    '116': {
        'address': 'Yosef Sapir 9',
        'favicon': '',
        'roomescape_id': 'jurassic-park',
        'name': 'Jurassic Park',
        'tel': '050-7247407',
        'y': 34.75185889999999,
        'people': '3-6',
        'trip': '',
        'city': 'Rishon LeZion',
        'x': 31.993796,
        'id': 116,
        'facebook': 'https://www.facebook.com/Enigmasecretroom/',
        'escapecard': '',
        'company': 'Enigma',
        'selected': true,
        'link': 'http://www.enigma-escaperooms.co.il/?portfolio_page=vintage-vinyl-house&utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.1'
    },
    '95': {
        'address': 'Derech HeHaruv',
        'favicon': '/static/Logos/questeam.png',
        'roomescape_id': 'the-x-ray-killer',
        'name': 'X-Ray Killer',
        'tel': '054-3037886',
        'y': 35.3098812,
        'people': '2-6',
        'trip': '',
        'city': 'Merhavia',
        'x': 32.604621,
        'id': 95,
        'facebook': 'https://www.facebook.com/questeamil',
        'escapecard': '',
        'company': 'Questeam',
        'selected': true,
        'link': 'http://www.questeam.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank-4/c192n',
        'review_score': '7.0'
    },
    '40': {
        'address': 'Haoman 22',
        'favicon': '/static/Logos/challengeroom.png',
        'roomescape_id': 'the-great-jailbreak',
        'name': 'The Great Jailbreak',
        'tel': '02-6485599',
        'y': 35.21371,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293983-d9564177-Reviews-Challenge_Room-Jerusalem_Jerusalem_District.html',
        'city': 'Jerusalem',
        'x': 31.768319,
        'id': 40,
        'facebook': 'https://www.facebook.com/challengerooms/',
        'escapecard': '',
        'company': 'Challenge Room',
        'selected': true,
        'link': 'http://www.thechallengerooms.com/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!escape-room/icaoz',
        'review_score': '8.3'
    },
    '60': {
        'address': 'Metsada 6',
        'favicon': '/static/Logos/gameon.png',
        'roomescape_id': 'egypt',
        'name': 'Ancient Egypt',
        'tel': '054-3550124',
        'y': 34.7958417,
        'people': '3-6',
        'trip': '',
        'city': 'Beer Sheva',
        'x': 31.2584658,
        'id': 60,
        'facebook': 'https://www.facebook.com/GameONescaperooms',
        'escapecard': '1',
        'company': 'GameOn',
        'selected': true,
        'link': 'http://www.gameon-escaperooms.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank/r1kuq',
        'review_score': '8.5'
    },
    '48': {
        'address': 'Emek Khefer 82',
        'favicon': '',
        'roomescape_id': 'the-police-station',
        'name': 'The Police Station',
        'tel': '053-7247736',
        'y': 34.8694374,
        'people': '2-5',
        'trip': '',
        'city': 'Netanya',
        'x': 32.3442071,
        'id': 48,
        'facebook': 'https://www.facebook.com/No-Exit-Escape-room-306191366242016/',
        'escapecard': '1',
        'company': 'No Exit',
        'selected': true,
        'link': 'http://noexit.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '6.6'
    },
    '43': {
        'address': 'Nirim 10',
        'favicon': '',
        'roomescape_id': 'trapped-in-time',
        'name': 'Trapped in Time',
        'tel': '054-3945120',
        'y': 34.7907291,
        'people': '2-6',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0630181,
        'id': 43,
        'facebook': 'https://www.facebook.com/MindRushEscapeChallenge',
        'escapecard': '',
        'company': 'MindRush',
        'selected': true,
        'link': 'http://www.mindrush.co.il/he/90?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.2'
    },
    '112': {
        'address': 'Tsahal 29',
        'favicon': '/static/Logos/escapezone.png',
        'roomescape_id': 'wonder-zone',
        'name': 'Wonder Zone',
        'tel': '08-9171769',
        'y': 34.5894522,
        'people': '2-5',
        'trip': '',
        'city': 'Ashkelon',
        'x': 31.6649826,
        'id': 112,
        'facebook': 'https://www.facebook.com/escapezonerehovot/',
        'escapecard': '',
        'company': 'Escape Zone',
        'selected': true,
        'link': 'http://www.escape-zone.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank-5/c07op',
        'review_score': '8.1'
    },
    '17': {
        'address': 'Ha-Rabi mi-Bakhrakh 14',
        'favicon': '/static/Logos/portaly.png',
        'roomescape_id': 'portal-y',
        'name': 'Alien Abduction',
        'tel': '058-6076070',
        'y': 34.7652209,
        'people': '2-8',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d8295133-Reviews-Portal_Y-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0578332,
        'id': 17,
        'facebook': 'https://www.facebook.com/PortalY.Israel',
        'escapecard': '1',
        'company': 'Portal Y',
        'selected': true,
        'link': 'http://www.portaly.club/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!alienabduction/tt2xi',
        'review_score': '8.6'
    },
    '82': {
        'address': "Lohamei HaGeta'ot 34",
        'favicon': '',
        'roomescape_id': '',
        'name': 'The Lost Treasure',
        'tel': '053-8286151',
        'y': 35.097026,
        'people': '2-6',
        'trip': '',
        'city': 'Nahariya',
        'x': 33.0004129,
        'id': 82,
        'facebook': 'https://www.facebook.com/Traproom.ISRAEL',
        'escapecard': '',
        'company': 'Trap Room',
        'selected': true,
        'link': 'http://www.traproom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank/ocm8c',
        'review_score': '-'
    },
    '89': {
        'address': 'Yosef Karo 19',
        'favicon': '/static/Logos/mysticroom.png',
        'roomescape_id': 'the-book-of-secrets',
        'name': 'The Book Of Secrets',
        'tel': '073-7280200',
        'y': 34.7913354,
        'people': '2-8',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0706533,
        'id': 89,
        'facebook': 'https://www.facebook.com/mysticroom',
        'escapecard': '',
        'company': 'Mystic Room',
        'selected': true,
        'link': 'http://mysticroom.co.il/reserve.php?roomId=2&utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '5.2'
    },
    '70': {
        'address': 'Freiman 20',
        'favicon': '/static/Logos/lockbox.png',
        'roomescape_id': 'baker-street',
        'name': 'Baker Street',
        'tel': '03-6163338',
        'y': 34.8143595,
        'people': '2-6',
        'trip': '',
        'city': 'Rishon LeZion',
        'x': 31.9748933,
        'id': 70,
        'facebook': 'https://www.facebook.com/SilvesterProductions/',
        'escapecard': '',
        'company': 'Lock Box',
        'selected': true,
        'link': 'http://lockbox.co.il/%D7%94%D7%96%D7%9E%D7%A0%D7%95%D7%AA/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '5.0'
    },
    '35': {
        'address': 'Jabotinsky 77',
        'favicon': '',
        'roomescape_id': 'jerusalem-treasure',
        'name': 'Jerusalem Treasure',
        'tel': '054-5313438',
        'y': 34.8127177,
        'people': '2-5',
        'trip': '',
        'city': 'Ramat Gan',
        'x': 32.0872881,
        'id': 35,
        'facebook': 'https://www.facebook.com/Step-by-Step-466688183536238/',
        'escapecard': '',
        'company': 'Step by Step',
        'selected': true,
        'link': 'http://stepbystep.org.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.8'
    },
    '88': {
        'address': 'Yosef Karo 19',
        'favicon': '/static/Logos/mysticroom.png',
        'roomescape_id': 'pharaohs-curse',
        'name': "Pharaoh's Curse",
        'tel': '073-7280200',
        'y': 34.7913354,
        'people': '2-6',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0706533,
        'id': 88,
        'facebook': 'https://www.facebook.com/mysticroom',
        'escapecard': '',
        'company': 'Mystic Room',
        'selected': true,
        'link': 'http://mysticroom.co.il/reserve.php?roomId=0&utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.4'
    },
    '33': {
        'address': 'Dizengoff 203',
        'favicon': '',
        'roomescape_id': 'the-african-stone',
        'name': 'Mystery of the African Stone',
        'tel': '058-6903600',
        'y': 34.775113,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7592183-Reviews-Out_Of_The_Box-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.08769,
        'id': 33,
        'facebook': 'https://www.facebook.com/boxgame.co.il',
        'escapecard': '1',
        'company': 'Out of the Box',
        'selected': true,
        'link': 'http://www.boxgame.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!africa/cyjva',
        'review_score': '8.1'
    },
    '16': {
        'address': 'Gershon Shatz 30',
        'favicon': '/static/Logos/escaperoom.png',
        'roomescape_id': 'robbery-of-the-century',
        'name': 'The Robbery of the Century',
        'tel': '077-7521376',
        'y': 34.7902594,
        'people': '2-5(x2)',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7351270-Reviews-Escape_Room_Israel-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0688466,
        'id': 16,
        'facebook': 'https://www.facebook.com/escaperoom.israel',
        'escapecard': '',
        'company': 'Escaperoom',
        'selected': true,
        'link': 'http://www.escaperoom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!escape-rooms-tel-aviv-hebrew/h9lwp',
        'review_score': '7.9'
    },
    '56': {
        'address': 'Hameyasdim 62',
        'favicon': 'http://baron-code.co.il/wp-content/uploads/2015/02/ZOFEN_LOGO_Slice_icon.ico',
        'roomescape_id': 'secrets-of-the-scroll',
        'name': 'Secrets of the Scroll',
        'tel': '072-2409004',
        'y': 34.9540235,
        'people': '3-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g609101-d7929535-Reviews-Baron_s_Code_Escape_Rooms-Zichron_Yaakov_Haifa_District.html',
        'city': 'Zichron Yakov',
        'x': 32.5743999,
        'id': 56,
        'facebook': 'https://www.facebook.com/bcescapegames',
        'escapecard': '',
        'company': 'Baron Code',
        'selected': true,
        'link': 'http://booking.baron-code.co.il/schedule/Baron_Code/SodotHamegila?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.2'
    },
    '21': {
        'address': "Ha'Bustan 35",
        'favicon': '/static/Logos/breakout.png',
        'roomescape_id': 'the-iranian-threat',
        'name': 'The Iranian Threat',
        'tel': '054-4244883',
        'y': 34.8445308,
        'people': '2-7',
        'trip': '',
        'city': 'Herzliya',
        'x': 32.1774372,
        'id': 21,
        'facebook': 'https://www.facebook.com/breakoutisrael',
        'escapecard': '1',
        'company': 'Breakout',
        'selected': true,
        'link': 'http://breakout.co.il?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.2'
    },
    '39': {
        'address': 'Ha-Melakha 4',
        'favicon': '',
        'roomescape_id': 'the-forest-cabin',
        'name': 'The Forest Cabin',
        'tel': '058-6015588',
        'y': 34.8784681,
        'people': '2-6',
        'trip': '',
        'city': 'Raanana',
        'x': 32.1977741,
        'id': 39,
        'facebook': 'https://www.facebook.com/Brain-Escape-הבקתה-ביער-1685762591660710',
        'escapecard': '1',
        'company': 'Brain Escape',
        'selected': true,
        'link': 'http://www.brainescape.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank/jlnd7',
        'review_score': '7.7'
    },
    '79': {
        'address': "Menorat HaMa'or 3",
        'favicon': '/static/Logos/beithaquest.png',
        'roomescape_id': 'stalker',
        'name': 'Stalker',
        'tel': '03-5535585',
        'y': 34.7963779,
        'people': '2-6',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0744848,
        'id': 79,
        'facebook': 'https://www.facebook.com/BeitQuest/',
        'escapecard': '',
        'company': 'Beit HaQuest',
        'selected': true,
        'link': 'http://beithaquest.co.il/stalker?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '5.7'
    },
    '109': {
        'address': "Ef'al 23",
        'favicon': '/static/Logos/breakout.png',
        'roomescape_id': 'camp',
        'name': 'Camp 23',
        'tel': '03-6193464',
        'y': 34.8474166,
        'people': '4-8',
        'trip': '',
        'city': 'Petah Tikva',
        'x': 32.095554,
        'id': 109,
        'facebook': 'https://www.facebook.com/breakoutisrael',
        'escapecard': '1',
        'company': 'Breakout',
        'selected': true,
        'link': 'http://breakout.co.il?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.4'
    },
    '31': {
        'address': 'Kalman Gavrielov 39',
        'favicon': 'https://static.wixstatic.com/media/26fd72_cbacc003aadb4347835e84c4e1dd3f3b.png/v1/fit/w_467,h_420,usm_0.66_1.00_0.01/26fd72_cbacc003aadb4347835e84c4e1dd3f3b.png',
        'roomescape_id': 'the-room-of-professor-rubinstein',
        'name': 'The Room of Professor Rubinstein',
        'tel': '053-2241594',
        'y': 34.7843978,
        'people': '2-6',
        'trip': '',
        'city': 'Rehovot',
        'x': 31.8882041,
        'id': 31,
        'facebook': 'https://www.facebook.com/Escape-Room-Rehovot-1078136592231363/',
        'escapecard': '1',
        'company': 'Golden Key',
        'selected': true,
        'link': 'http://www.mygoldenkey.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank/tf84k',
        'review_score': '5.5'
    },
    '6': {
        'address': 'Ha-Hashmonaim 100',
        'favicon': '',
        'roomescape_id': 'the-chase',
        'name': 'The Chase',
        'tel': '03-5531194',
        'y': 34.7868952,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7917881-Reviews-Questomania-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0692659,
        'id': 6,
        'facebook': 'https://www.facebook.com/questomaniaIsrael',
        'escapecard': '',
        'company': 'Questomania',
        'selected': true,
        'link': 'https://www.questomania.co.il/shop/total-loss/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.5'
    },
    '4': {
        'address': 'Abulafiya 25',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'imaginarium',
        'name': 'Imaginarium',
        'tel': '054-9557666',
        'y': 34.7695098,
        'people': '2-4',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0520306,
        'id': 4,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://www.exitroom.co.il/rooms/imaginarium-2?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.9'
    },
    '120': {
        'address': 'Ha-Namal 6',
        'favicon': '/static/Logos/imitator.png',
        'roomescape_id': '',
        'name': 'Imitator',
        'tel': '054-2120747',
        'y': 35.002046,
        'people': '2-4',
        'trip': '',
        'city': 'Haifa',
        'x': 32.8177825,
        'id': 120,
        'facebook': 'https://www.facebook.com/The-Game-quest-1526251894343904',
        'escapecard': '',
        'company': 'The Game',
        'selected': true,
        'link': 'http://haifa-game.com/schedule/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '-'
    },
    '38': {
        'address': 'Bezalel 12',
        'favicon': '/static/Logos/escaperoom.png',
        'roomescape_id': 'escape-from-terrorist-hands',
        'name': 'Escape from Terrorists',
        'tel': '03-9773444',
        'y': 34.80136480000001,
        'people': '2-4',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g297761-d9457059-Reviews-Secret_Area_Quest-Ramat_Gan_Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Ramat Gan',
        'x': 32.0865858,
        'id': 38,
        'facebook': 'https://www.facebook.com/SecretAreaQuest/',
        'escapecard': '',
        'company': 'Escaperoom',
        'selected': true,
        'link': 'http://www.escaperoom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!escape-room-ramatgan-hebrew/m3v6o',
        'review_score': '8.2'
    },
    '74': {
        'address': 'Frumkin 5',
        'favicon': '',
        'roomescape_id': 'image-of-a-murderer',
        'name': 'Image of a Murderer',
        'tel': '054-2221606',
        'y': 34.8838715,
        'people': '2-4',
        'trip': '',
        'city': 'Petah Tikva',
        'x': 32.0924353,
        'id': 74,
        'facebook': 'https://www.facebook.com/%D7%97%D7%93%D7%A8-%D7%91%D7%A8%D7%99%D7%97%D7%94-%D7%9E%D7%95%D7%A2%D7%93%D7%95%D7%9F-%D7%94%D7%92%D7%95%D7%9C%D7%92%D7%9C%D7%95%D7%AA-1694861820798644/',
        'escapecard': '',
        'company': 'Skull Club',
        'selected': true,
        'link': 'http://hertk.com/booking/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.6'
    },
    '28': {
        'address': 'HaMischar 1',
        'favicon': '',
        'roomescape_id': 'secretroomashdod',
        'name': 'Back to the USSR',
        'tel': '052-7266852',
        'y': 34.645274,
        'people': '2-5',
        'trip': '',
        'city': 'Ashdod',
        'x': 31.807274,
        'id': 28,
        'facebook': 'https://www.facebook.com/SecretroomAshdod',
        'escapecard': '',
        'company': 'Secret Room',
        'selected': true,
        'link': 'http://secretroom.co.il/quests/nazad-v-sssr/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.2'
    },
    '18': {
        'address': 'HaTikshoret 5',
        'favicon': '/static/Logos/exitgame.png',
        'roomescape_id': 'time-machine',
        'name': 'Time Machine',
        'tel': '058-5595577',
        'y': 34.657145,
        'people': '3-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g1137841-d7751597-Reviews-ExitGame_Israel-Ashdod_Southern_District.html',
        'city': 'Ashdod',
        'x': 31.813712,
        'id': 18,
        'facebook': 'https://www.facebook.com/exitgame1',
        'escapecard': '1',
        'company': 'Exit Game',
        'selected': true,
        'link': 'http://www.exitgame.co.il/he/Games/Room/1?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.9'
    },
    '13': {
        'address': 'Tchernichovsky 26',
        'favicon': '',
        'roomescape_id': 'part-ii-the-crime',
        'name': 'The Crime',
        'tel': '03-3741695',
        'y': 34.7730814,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7191670-Reviews-Locked-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0742345,
        'id': 13,
        'facebook': 'https://www.facebook.com/lockedgames',
        'escapecard': '',
        'company': 'Locked',
        'selected': true,
        'link': 'http://www.locked-games.com/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!----/cf61',
        'review_score': '7.3'
    },
    '92': {
        'address': "HaTa'as 24",
        'favicon': '',
        'roomescape_id': 'hobbit',
        'name': 'The Hobbit',
        'tel': '054-6369863',
        'y': 34.9274285,
        'people': '2-7',
        'trip': '',
        'city': 'Kfar Saba',
        'x': 32.1770154,
        'id': 92,
        'facebook': 'https://www.facebook.com/Xcape-1090176937691642',
        'escapecard': '1',
        'company': 'Xcape',
        'selected': true,
        'link': 'http://xcape.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.5'
    },
    '103': {
        'address': 'Eliyahu Eitan 24',
        'favicon': '/static/Logos/twisted.png',
        'roomescape_id': 'twisted-mind',
        'name': 'Return of the Mummy',
        'tel': '054-8196909',
        'y': 34.7630147,
        'people': '2-6',
        'trip': '',
        'city': 'Rishon LeZion',
        'x': 31.9934266,
        'id': 103,
        'facebook': 'https://www.facebook.com/backofthemummy/',
        'escapecard': '',
        'company': 'Twisted Mind',
        'selected': true,
        'link': 'http://www.twistedmindescaperoom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.1'
    },
    '72': {
        'address': 'Maskit 9',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'secret-files',
        'name': 'Secret Files',
        'tel': '054-6300617',
        'y': 34.8116132,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Herzliya',
        'x': 32.1655795,
        'id': 72,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://exitroom.co.il/rooms/secret-files/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.4'
    },
    '106': {
        'address': 'Hahistadrut 19',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'bank-robbery',
        'name': 'Bank Robbery',
        'tel': '054-8132233',
        'y': 34.7880849,
        'people': '2-7',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Beer Sheva',
        'x': 31.2388211,
        'id': 106,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://exitroom.co.il/rooms/bank-beersheva?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.9'
    },
    '77': {
        'address': "Menorat HaMa'or 3",
        'favicon': '/static/Logos/beithaquest.png',
        'roomescape_id': 'pirate-hut',
        'name': 'Pirate Hut',
        'tel': '03-5535585',
        'y': 34.7963779,
        'people': '2-6',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0744848,
        'id': 77,
        'facebook': 'https://www.facebook.com/BeitQuest/',
        'escapecard': '',
        'company': 'Beit HaQuest',
        'selected': true,
        'link': 'http://beithaquest.co.il/pirate?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '-'
    },
    '24': {
        'address': 'Yafo 97',
        'favicon': '',
        'roomescape_id': 'race-to-the-million',
        'name': 'Race to the Million',
        'tel': '058-4579797',
        'y': 35.2148956,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293983-d7717662-Reviews-Secret_Room_Jerusalem-Jerusalem_Jerusalem_District.html',
        'city': 'Jerusalem',
        'x': 31.7842936,
        'id': 24,
        'facebook': 'https://www.facebook.com/SecretroomJerusalem',
        'escapecard': '',
        'company': 'Secret Room',
        'selected': true,
        'link': 'http://secretroom.co.il/en/quests/v-pogone-za-millionom/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.3'
    },
    '42': {
        'address': 'Nahalat Binyamin 68',
        'favicon': '/static/Logos/escapetlv.png',
        'roomescape_id': 'the-dark-order',
        'name': 'The Dark Order',
        'tel': '054-7516124',
        'y': 34.7724722,
        'people': '2-6',
        'trip': 'https://www.tripadvisor.co.il/Attraction_Review-g293984-d9716133-Reviews-Escape_TLV-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0613171,
        'id': 42,
        'facebook': 'https://www.facebook.com/EscapeTLV',
        'escapecard': '',
        'company': 'Escape TLV',
        'selected': true,
        'link': 'http://escapetlv.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.0'
    },
    '44': {
        'address': 'Hanan Oppenheimer 10',
        'favicon': '',
        'roomescape_id': 'the-iron-throne',
        'name': 'The Iron Throne',
        'tel': '08-8606551',
        'y': 34.8069407,
        'people': '2-6',
        'trip': '',
        'city': 'Rehovot',
        'x': 31.9107585,
        'id': 44,
        'facebook': 'https://www.facebook.com/Cube-Israel-Escape-room-959631307393761/',
        'escapecard': '1',
        'company': 'Cube',
        'selected': true,
        'link': 'http://www.cube-israel.co.il?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.2'
    },
    '49': {
        'address': 'Sderot HaHistadrut 34',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'bank-robbery',
        'name': 'Bank Robbery',
        'tel': '053-6224799',
        'y': 35.0336836,
        'people': '2-7',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Haifa',
        'x': 32.7907495,
        'id': 49,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://exitroom.co.il/rooms/bank-robber?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.9'
    },
    '25': {
        'address': 'Derech bar Yehuda 195',
        'favicon': '',
        'roomescape_id': 'the-asylum',
        'name': 'The Asylum',
        'tel': '054-9281393',
        'y': 35.0357116,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293982-d8475435-Reviews-Questline-Haifa_Haifa_District.html',
        'city': 'Nesher',
        'x': 32.7808389,
        'id': 25,
        'facebook': 'https://www.facebook.com/Questlineil',
        'escapecard': '',
        'company': 'Questline',
        'selected': true,
        'link': 'http://questline.co.il/en/booking.html?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.4'
    },
    '15': {
        'address': 'Dizengoff 203',
        'favicon': '',
        'roomescape_id': 'behind-the-scenes',
        'name': 'Behind the Scenes',
        'tel': '058-6903600',
        'y': 34.775113,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7592183-Reviews-Out_Of_The_Box-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.08769,
        'id': 15,
        'facebook': 'https://www.facebook.com/boxgame.co.il',
        'escapecard': '1',
        'company': 'Out of the Box',
        'selected': true,
        'link': 'http://www.boxgame.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!theatermystery/c1vz0',
        'review_score': '7.6'
    },
    '78': {
        'address': "Menorat HaMa'or 3",
        'favicon': '/static/Logos/beithaquest.png',
        'roomescape_id': 'morgue',
        'name': 'Morgue',
        'tel': '03-5535585',
        'y': 34.7963779,
        'people': '2-6',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0744848,
        'id': 78,
        'facebook': 'https://www.facebook.com/BeitQuest/',
        'escapecard': '',
        'company': 'Beit HaQuest',
        'selected': true,
        'link': 'http://beithaquest.co.il/mahon-patologi?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '5.4'
    },
    '57': {
        'address': "Sha'ar Palmer 1",
        'favicon': '',
        'roomescape_id': 'race-to-the-million-haifa',
        'name': 'Race to the Million',
        'tel': '058-5579797',
        'y': 34.999997,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293983-d7717662-Reviews-Secret_Room_Jerusalem-Jerusalem_Jerusalem_District.html',
        'city': 'Haifa',
        'x': 32.8197906,
        'id': 57,
        'facebook': 'https://www.facebook.com/secretroomhaifa',
        'escapecard': '',
        'company': 'Secret Room',
        'selected': true,
        'link': 'http://secretroom.co.il/quests/v-pogone-za-millionom-haifa?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.4'
    },
    '45': {
        'address': 'Hanan Oppenheimer 10',
        'favicon': '',
        'roomescape_id': 'gotham-general-hospital',
        'name': 'Gotham - General Hospital',
        'tel': '08-8606551',
        'y': 34.8069407,
        'people': '2-6',
        'trip': '',
        'city': 'Rehovot',
        'x': 31.9107585,
        'id': 45,
        'facebook': 'https://www.facebook.com/Cube-Israel-Escape-room-959631307393761/',
        'escapecard': '1',
        'company': 'Cube',
        'selected': true,
        'link': 'http://www.cube-israel.co.il?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.6'
    },
    '10': {
        'address': 'Ben Shatakh 9',
        'favicon': '',
        'roomescape_id': 'boardwalk-empire',
        'name': 'Boardwalk Empire',
        'tel': '077-3610000',
        'y': 34.7580668,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7928499-Reviews-Brainit_Real_Life_Room_Escape_Game-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0555213,
        'id': 10,
        'facebook': 'https://www.facebook.com/brainit.co.il',
        'escapecard': '',
        'company': 'Brainit',
        'selected': true,
        'link': 'http://brainit.co.il/he/game/boardwalk_empire/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.0'
    },
    '85': {
        'address': 'Tsaftsafa 1',
        'favicon': '',
        'roomescape_id': '',
        'name': 'Wild West',
        'tel': '054-9120906',
        'y': 35.174221,
        'people': '2-5',
        'trip': '',
        'city': 'Ramat Yishai',
        'x': 32.706662,
        'id': 85,
        'facebook': 'https://www.facebook.com/EmeQuest-1682999698620226/',
        'escapecard': '',
        'company': 'EmeQuest',
        'selected': true,
        'link': 'http://www.emequest.com/he/escape-rooms/16?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '-'
    },
    '54': {
        'address': 'Ha-Hashmonaim 100',
        'favicon': '',
        'roomescape_id': 'the-russian-prison',
        'name': 'The Russian Prison',
        'tel': '03-5531194',
        'y': 34.7868952,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7917881-Reviews-Questomania-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0692659,
        'id': 54,
        'facebook': 'https://www.facebook.com/questomaniaIsrael',
        'escapecard': '',
        'company': 'Questomania',
        'selected': true,
        'link': 'https://www.questomania.co.il/shop/russian-police-station/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.7'
    },
    '99': {
        'address': 'HaNotrim 1',
        'favicon': '/static/Logos/timesquare.png',
        'roomescape_id': 'time-square-atlantis',
        'name': 'Atlantis',
        'tel': '058-6440641',
        'y': 34.5848163,
        'people': '2-6',
        'trip': '',
        'city': 'Ashkelon',
        'x': 31.6653356,
        'id': 99,
        'facebook': 'https://www.facebook.com/Time-Square-Ashkelon-טיים-סקוואר-אשקלון-225437911143150/',
        'escapecard': '',
        'company': 'Time Square',
        'selected': true,
        'link': 'http://timesquare.co.il/%D7%90%D7%98%D7%9C%D7%A0%D7%98%D7%99%D7%A1/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.3'
    },
    '46': {
        'address': 'Yad Haruzim 16',
        'favicon': '',
        'roomescape_id': 'king-solomons-mines',
        'name': "King's Solomon Mines",
        'tel': '02-6480229',
        'y': 35.216273,
        'people': '2-6',
        'trip': '',
        'city': 'Jerusalem',
        'x': 31.7517079,
        'id': 46,
        'facebook': 'https://www.facebook.com/Bquest-972506959459105/',
        'escapecard': '',
        'company': 'Bquest',
        'selected': true,
        'link': 'http://bquest.co.il/solomon-mines?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.8'
    },
    '47': {
        'address': 'Yad Haruzim 16',
        'favicon': '',
        'roomescape_id': 'unequivocal-threat',
        'name': 'Unequivocal Threat',
        'tel': '02-6480229',
        'y': 35.216273,
        'people': '2-6',
        'trip': '',
        'city': 'Jerusalem',
        'x': 31.7517079,
        'id': 47,
        'facebook': 'https://www.facebook.com/Bquest-972506959459105/',
        'escapecard': '',
        'company': 'Bquest',
        'selected': true,
        'link': 'http://bquest.co.il/unequivocal-threat?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.2'
    },
    '12': {
        'address': 'Tchernichovsky 26',
        'favicon': '',
        'roomescape_id': 'part-i-the-secret-lab',
        'name': 'Secret Lab',
        'tel': '03-3741695',
        'y': 34.7730814,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7191670-Reviews-Locked-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0742345,
        'id': 12,
        'facebook': 'https://www.facebook.com/lockedgames',
        'escapecard': '',
        'company': 'Locked',
        'selected': true,
        'link': 'http://www.locked-games.com/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!------/bmp5r',
        'review_score': '8.1'
    },
    '29': {
        'address': 'David Saharov 17',
        'favicon': '/static/Logos/saw.png',
        'roomescape_id': 'saw',
        'name': 'Saw',
        'tel': '054-9103282',
        'y': 34.7716807,
        'people': '2-7',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g2561658-d8876010-Reviews-Lostroom-Rishon_Lezion_Central_District.html',
        'city': 'Rishon LeZion',
        'x': 31.99087759999999,
        'id': 29,
        'facebook': 'https://www.facebook.com/Lostroom.Rishon',
        'escapecard': '1',
        'company': 'Lostroom',
        'selected': true,
        'link': 'http://www.lostroom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!saw/v4f1f',
        'review_score': '9.1'
    },
    '114': {
        'address': 'Lishanski 18',
        'favicon': '/static/Logos/escapezone.png',
        'roomescape_id': 'sircuszonederano',
        'name': 'Circus Zone-Derano',
        'tel': '03-5798554',
        'y': 34.7667985,
        'people': '2-5(x2)',
        'trip': '',
        'city': 'Rishon LeZion',
        'x': 31.9920572,
        'id': 114,
        'facebook': 'https://www.facebook.com/escapezonerehovot/',
        'escapecard': '',
        'company': 'Escape Zone',
        'selected': true,
        'link': 'http://www.escape-zone.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank-3/cy19e',
        'review_score': '7.9'
    },
    '93': {
        'address': 'Maccabi 5',
        'favicon': '/static/Logos/60min.png',
        'roomescape_id': '',
        'name': 'The Note',
        'tel': '04-8383991',
        'y': 35.0766286,
        'people': '2-6',
        'trip': '',
        'city': 'Kiryat Motzkin',
        'x': 32.8267817,
        'id': 93,
        'facebook': 'https://www.facebook.com/Escape-Room-635499946606148/',
        'escapecard': '',
        'company': '60min',
        'selected': true,
        'link': 'http://60min.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '-'
    },
    '69': {
        'address': 'Hapelah 3',
        'favicon': '',
        'roomescape_id': 'artificial-intelligence',
        'name': 'Tesys 2.0',
        'tel': '03-3741695',
        'y': 34.78176759999999,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7191670-Reviews-Locked-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0852999,
        'id': 69,
        'facebook': 'https://www.facebook.com/lockedgames',
        'escapecard': '',
        'company': 'Locked',
        'selected': true,
        'link': 'http://www.locked-games.com/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!-------------/mkuj2',
        'review_score': '8.5'
    },
    '64': {
        'address': 'Moriya 58',
        'favicon': '/static/Logos/enigmatic.png',
        'roomescape_id': 'kohinoor',
        'name': ' Kohinoor',
        'tel': '052-5745804',
        'y': 34.9843392,
        'people': '2-6',
        'trip': '',
        'city': 'Haifa',
        'x': 32.7964951,
        'id': 64,
        'facebook': 'https://www.facebook.com/Enigmatic-1683948811862615',
        'escapecard': '',
        'company': 'Enigmatic',
        'selected': true,
        'link': 'http://www.enigmatic.co.il/he/rooms/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.4'
    },
    '104': {
        'address': 'Ben Gurion 22',
        'favicon': '',
        'roomescape_id': 'the-mona-lisa-robbery',
        'name': 'The Mona Lisa Robbery',
        'tel': '09-8874499',
        'y': 35.0750083,
        'people': '2-6',
        'trip': '',
        'city': 'Herzliya',
        'x': 32.8101588,
        'id': 104,
        'facebook': 'https://www.facebook.com/nowayoutisrael/',
        'escapecard': '1',
        'company': 'Nowayout',
        'selected': true,
        'link': 'http://www.nowayout.co.il/rooms/mona-lisa/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.6'
    },
    '58': {
        'address': 'Schlesinger 1',
        'favicon': '/static/Logos/livequest.png',
        'roomescape_id': 'breaking-bad',
        'name': 'Breaking Bad',
        'tel': '054-7161311',
        'y': 34.6704361,
        'people': '2-5',
        'trip': '',
        'city': 'Ashdod',
        'x': 31.8185198,
        'id': 58,
        'facebook': 'https://www.facebook.com/Live-Quest-1006093796129102/',
        'escapecard': '',
        'company': 'Live Quest',
        'selected': true,
        'link': 'http://www.livequest.co.il/משחק-1?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.3'
    },
    '102': {
        'address': 'Menachem Begin 112',
        'favicon': '',
        'roomescape_id': 'piratescape',
        'name': ' The Pirate Code',
        'tel': '058-5588007',
        'y': 34.7890407,
        'people': '2-6(x2)',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0705995,
        'id': 102,
        'facebook': 'https://www.facebook.com/PiratEscapeIsrael',
        'escapecard': '1',
        'company': 'Pirate Escape',
        'selected': true,
        'link': 'http://www.piratescape.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank/nfm34',
        'review_score': '9.3'
    },
    '96': {
        'address': 'Ha-Yetsira 10',
        'favicon': '',
        'roomescape_id': 'the-connection',
        'name': 'The Connection',
        'tel': '09-9552277',
        'y': 34.8769265,
        'people': '2-6',
        'trip': '',
        'city': 'Raanana',
        'x': 32.1950134,
        'id': 96,
        'facebook': 'https://www.facebook.com/getawayisrael/',
        'escapecard': '',
        'company': 'Getaway',
        'selected': true,
        'link': 'http://www.get-away.co.il/Room/7?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.9'
    },
    '84': {
        'address': 'Tsaftsafa 1',
        'favicon': '',
        'roomescape_id': 'pink-panther-diamond',
        'name': 'Pink Panther',
        'tel': '054-9120906',
        'y': 35.174221,
        'people': '2-7',
        'trip': '',
        'city': 'Ramat Yishai',
        'x': 32.706662,
        'id': 84,
        'facebook': 'https://www.facebook.com/EmeQuest-1682999698620226/',
        'escapecard': '',
        'company': 'EmeQuest',
        'selected': true,
        'link': 'http://www.emequest.com/he/escape-rooms/15?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '-'
    },
    '36': {
        'address': 'Carlebach 3',
        'favicon': '/static/Logos/escapegame.png',
        'roomescape_id': 'kgb-still-watching-you',
        'name': 'KGB - Still Watching You',
        'tel': '055-6688441',
        'y': 34.7834808,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d8844274-Reviews-Escape_Game_Israel-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0663765,
        'id': 36,
        'facebook': 'https://www.facebook.com/EscapeGame.il/',
        'escapecard': '',
        'company': 'Escape Game',
        'selected': true,
        'link': 'http://www.escape-game.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.3'
    },
    '9': {
        'address': 'Derech Menachem Begin 25',
        'favicon': '',
        'roomescape_id': 'the-dark-side-of-the-art',
        'name': 'Dark Side of the Art',
        'tel': '054-2809087',
        'y': 34.780418,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d8050752-Reviews-Quest_and_Quest-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0638418,
        'id': 9,
        'facebook': 'https://www.facebook.com/questandquest',
        'escapecard': '1',
        'company': 'Quest & Quest',
        'selected': true,
        'link': 'http://www.escaperoom-quest.co.il/הצד-האפל-של-האומנות?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.6'
    },
    '3': {
        'address': 'Jabotinsky 83',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'antidote-mission',
        'name': 'Antidote Mission',
        'tel': '054-2870767',
        'y': 34.8131346,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Ramat Gan',
        'x': 32.0875532,
        'id': 3,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://www.exitroom.co.il/rooms/antidote-mission/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.1'
    },
    '67': {
        'address': 'Ha-Melakha 8',
        'favicon': '',
        'roomescape_id': 'the-dentists-clinic',
        'name': "The Dentist's Clinic",
        'tel': '054-9546883',
        'y': 34.8584643,
        'people': '2-6',
        'trip': '',
        'city': 'Netanya',
        'x': 32.2780241,
        'id': 67,
        'facebook': 'https://www.facebook.com/BXperia-%D7%97%D7%93%D7%A8%D7%99-%D7%91%D7%A8%D7%99%D7%97%D7%94-528788040624202/',
        'escapecard': '',
        'company': 'BXperia',
        'selected': true,
        'link': 'http://bxperia.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.0'
    },
    '87': {
        'address': 'Giborei Israel 24',
        'favicon': '',
        'roomescape_id': 'heroes',
        'name': 'Heroes',
        'tel': '052-8473359',
        'y': 34.8608186,
        'people': '2-10',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7928499-Reviews-Brainit_Real_Life_Room_Escape_Game-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Netanya',
        'x': 32.2802704,
        'id': 87,
        'facebook': 'https://www.facebook.com/brainit.co.il',
        'escapecard': '',
        'company': 'Brainit',
        'selected': true,
        'link': 'http://brainit.co.il/f2/room/heroes/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.9'
    },
    '14': {
        'address': 'Dizengoff 203',
        'favicon': '',
        'roomescape_id': 'wine-cellar',
        'name': 'Wine Cellar',
        'tel': '058-6903600',
        'y': 34.775113,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7592183-Reviews-Out_Of_The_Box-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.08769,
        'id': 14,
        'facebook': 'https://www.facebook.com/boxgame.co.il',
        'escapecard': '1',
        'company': 'Out of the Box',
        'selected': true,
        'link': 'http://www.boxgame.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!quest11/c24pv',
        'review_score': '7.8'
    },
    '27': {
        'address': 'Galgalei ha-Plada 6',
        'favicon': '',
        'roomescape_id': 'fordow-cyber-attack',
        'name': 'ForDow - Cyber Attack',
        'tel': '09-8617767',
        'y': 34.8085987,
        'people': '2-5',
        'trip': '',
        'city': 'Herzliya',
        'x': 32.1631237,
        'id': 27,
        'facebook': 'https://www.facebook.com/BrainEffect-%D7%91%D7%A8%D7%99%D7%99%D7%9F-%D7%90%D7%A4%D7%A7%D7%98-1484714051839851/',
        'escapecard': '',
        'company': 'BrainEffect',
        'selected': true,
        'link': 'http://braineffect.co.il/fordow/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.1'
    },
    '107': {
        'address': 'Hadasa 53',
        'favicon': '/static/Logos/escaperoom.png',
        'roomescape_id': 'doomsday',
        'name': 'Doomsday',
        'tel': '08-6716772',
        'y': 34.7901618,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7351270-Reviews-Escape_Room_Israel-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Beer Sheva',
        'x': 31.2408405,
        'id': 107,
        'facebook': 'https://www.facebook.com/Escape-Room-Beer-Sheva-%D7%90%D7%A1%D7%A7%D7%99%D7%99%D7%A4-%D7%A8%D7%95%D7%9D-%D7%91%D7%90%D7%A8-%D7%A9%D7%91%D7%A2-106744109738170/',
        'escapecard': '',
        'company': 'Escaperoom',
        'selected': true,
        'link': 'http://www.escaperoom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!doom-day-beer-sheva-escape-room/ul9qg',
        'review_score': '8.9'
    },
    '32': {
        'address': 'Ben Shatakh 9',
        'favicon': '',
        'roomescape_id': 'trapped',
        'name': 'Trapped',
        'tel': '077-3610000',
        'y': 34.7580668,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7928499-Reviews-Brainit_Real_Life_Room_Escape_Game-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0555213,
        'id': 32,
        'facebook': 'https://www.facebook.com/brainit.co.il',
        'escapecard': '',
        'company': 'Brainit',
        'selected': true,
        'link': 'http://brainit.co.il/he/game/trapped/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.7'
    },
    '59': {
        'address': 'HaBarzel 31',
        'favicon': '/static/Logos/question.png',
        'roomescape_id': 'casino-robbery',
        'name': 'Casino Robbery',
        'tel': '072-2500720',
        'y': 34.8411217,
        'people': '2-5(x2)',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.1104408,
        'id': 59,
        'facebook': 'https://www.facebook.com/QuestionEscapeRooms',
        'escapecard': '',
        'company': 'Question',
        'selected': true,
        'link': 'http://www.quest-ion.co.il?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.5'
    },
    '68': {
        'address': 'Ha-Bonim Ha-Khofshiyim 11',
        'favicon': '',
        'roomescape_id': 'the-secret-of-the-gallery',
        'name': 'The Secret of the Gallery',
        'tel': '050-9252847',
        'y': 35.039323,
        'people': '2-7',
        'trip': '',
        'city': 'Haifa',
        'x': 32.788302,
        'id': 68,
        'facebook': 'https://www.facebook.com/escapeChallengeQuest',
        'escapecard': '',
        'company': 'Escape Challenge',
        'selected': true,
        'link': 'http://escapechallenge.co.il/main?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.1'
    },
    '94': {
        'address': 'Derech HeHaruv',
        'favicon': '/static/Logos/questeam.png',
        'roomescape_id': 'siryan-captivity',
        'name': 'Syrian Captivity',
        'tel': '054-3037886',
        'y': 35.3098812,
        'people': '2-6',
        'trip': '',
        'city': 'Merhavia',
        'x': 32.604621,
        'id': 94,
        'facebook': 'https://www.facebook.com/questeamil',
        'escapecard': '',
        'company': 'Questeam',
        'selected': true,
        'link': 'http://www.questeam.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank-3/jxdu5',
        'review_score': '7.1'
    },
    '55': {
        'address': 'Hameyasdim 62',
        'favicon': 'http://baron-code.co.il/wp-content/uploads/2015/02/ZOFEN_LOGO_Slice_icon.ico',
        'roomescape_id': 'barons-treasure',
        'name': "Baron's Treasure",
        'tel': '072-2409004',
        'y': 34.9540235,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g609101-d7929535-Reviews-Baron_s_Code_Escape_Rooms-Zichron_Yaakov_Haifa_District.html',
        'city': 'Zichron Yakov',
        'x': 32.5743999,
        'id': 55,
        'facebook': 'https://www.facebook.com/bcescapegames',
        'escapecard': '',
        'company': 'Baron Code',
        'selected': true,
        'link': 'http://booking.baron-code.co.il/schedule/Baron_Code/MatmonHabaron?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.2'
    },
    '113': {
        'address': 'Tsahal 29',
        'favicon': '/static/Logos/escapezone.png',
        'roomescape_id': 'the-chemist',
        'name': 'The Chemist',
        'tel': '08-9171769',
        'y': 34.5894522,
        'people': '2-5',
        'trip': '',
        'city': 'Ashkelon',
        'x': 31.6649826,
        'id': 113,
        'facebook': 'https://www.facebook.com/escapezonerehovot/',
        'escapecard': '',
        'company': 'Escape Zone',
        'selected': true,
        'link': 'http://www.escape-zone.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank-5/c07op',
        'review_score': '7.9'
    },
    '22': {
        'address': 'Shamai 19',
        'favicon': '/static/Logos/escaperoom.png',
        'roomescape_id': 'robbery-of-the-century-jerusalem',
        'name': 'The Robbery of the Century',
        'tel': '02-6535010',
        'y': 35.2186588,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293983-d8615727-Reviews-Escape_Room_Jerusalem-Jerusalem_Jerusalem_District.html',
        'city': 'Jerusalem',
        'x': 31.7812102,
        'id': 22,
        'facebook': 'https://www.facebook.com/escaperoom.israel',
        'escapecard': '',
        'company': 'Escaperoom',
        'selected': true,
        'link': 'http://www.escaperoom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!escape-room-jerusalem-hebrew/bcy7w',
        'review_score': '8.3'
    },
    '11': {
        'address': 'Tozeret HaAretz 16',
        'favicon': '',
        'roomescape_id': 'the-syrian-spy-room',
        'name': 'The Syrian Spy Room',
        'tel': '03-5040830',
        'y': 34.7973181,
        'people': '2-5(x2)',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7383209-Reviews-Escapeit-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0724511,
        'id': 11,
        'facebook': 'https://www.facebook.com/escapeitisrael',
        'escapecard': '',
        'company': 'Escapeit',
        'selected': true,
        'link': 'http://www.escapeit.co.il/הזמנות?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.5'
    },
    '2': {
        'address': 'Allenby 65',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'haunted-house',
        'name': 'Haunted House',
        'tel': '053-5224340',
        'y': 34.7710173,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0681333,
        'id': 2,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://www.exitroom.co.il/rooms/haunted-house/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.9'
    },
    '50': {
        'address': "Eli'ezer Ben Yehuda 4",
        'favicon': '/static/Logos/escapezone.png',
        'roomescape_id': 'wonder-zone',
        'name': 'Wonder Zone',
        'tel': '08-8659966',
        'y': 34.8092745,
        'people': '2-5',
        'trip': '',
        'city': 'Rehovot',
        'x': 31.9021206,
        'id': 50,
        'facebook': 'https://www.facebook.com/escapezonerehovot/',
        'escapecard': '',
        'company': 'Escape Zone',
        'selected': true,
        'link': 'http://www.escape-zone.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank-2/js79d',
        'review_score': '8.1'
    },
    '86': {
        'address': 'Beit Hilel 7',
        'favicon': '/static/Logos/escaperoom.png',
        'roomescape_id': 'titanic',
        'name': 'Titanic',
        'tel': '077-7521376',
        'y': 34.7897598,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7351270-Reviews-Escape_Room_Israel-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0695376,
        'id': 86,
        'facebook': 'https://www.facebook.com/escaperoom.israel',
        'escapecard': '',
        'company': 'Escaperoom',
        'selected': true,
        'link': 'http://www.escaperoom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!titanic-escape-room-telaviv-hebrew/joh2i',
        'review_score': '7.0'
    },
    '7': {
        'address': 'Ha-Hashmonaim 100',
        'favicon': '',
        'roomescape_id': 'zombies-attack',
        'name': 'Zombie Attack',
        'tel': '03-5531194',
        'y': 34.7868952,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7917881-Reviews-Questomania-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0692659,
        'id': 7,
        'facebook': 'https://www.facebook.com/questomaniaIsrael',
        'escapecard': '',
        'company': 'Questomania',
        'selected': true,
        'link': 'https://www.questomania.co.il/shop/zombie-attack/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.2'
    },
    '115': {
        'address': 'Galgalei ha-Plada 6',
        'favicon': '',
        'roomescape_id': 'the-matrix',
        'name': 'Matrix',
        'tel': '09-8617767',
        'y': 34.8085987,
        'people': '2-5',
        'trip': '',
        'city': 'Herzliya',
        'x': 32.1631237,
        'id': 115,
        'facebook': 'https://www.facebook.com/BrainEffect-%D7%91%D7%A8%D7%99%D7%99%D7%9F-%D7%90%D7%A4%D7%A7%D7%98-1484714051839851/',
        'escapecard': '',
        'company': 'BrainEffect',
        'selected': true,
        'link': 'http://braineffect.co.il/matrix/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '-'
    },
    '90': {
        'address': 'Beit Hilel 7',
        'favicon': '/static/Logos/gravity.png',
        'roomescape_id': 'gravity',
        'name': 'Gravity',
        'tel': '052-3232293',
        'y': 34.7897598,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7351270-Reviews-Escape_Room_Israel-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0695376,
        'id': 90,
        'facebook': 'http://www.facebook.com/cyberquest.israel/',
        'escapecard': '',
        'company': 'CyberQuest',
        'selected': true,
        'link': 'http://www.escaperoom.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!cyber-quest-main/iogln',
        'review_score': '6.9'
    },
    '75': {
        'address': 'Yosef Sapir 9',
        'favicon': '',
        'roomescape_id': 'indiana-jones',
        'name': 'Indiana Jones',
        'tel': '050-7247407',
        'y': 34.75185889999999,
        'people': '2-6',
        'trip': '',
        'city': 'Rishon LeZion',
        'x': 31.993796,
        'id': 75,
        'facebook': 'https://www.facebook.com/Enigmasecretroom/',
        'escapecard': '',
        'company': 'Enigma',
        'selected': true,
        'link': 'http://www.enigma-escaperooms.co.il/?portfolio_page=art-week-2014-malmo&utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.2'
    },
    '51': {
        'address': "Eli'ezer Ben Yehuda 4",
        'favicon': '/static/Logos/escapezone.png',
        'roomescape_id': 'the-chemist',
        'name': 'The Chemist',
        'tel': '08-8659966',
        'y': 34.8092745,
        'people': '2-5',
        'trip': '',
        'city': 'Rehovot',
        'x': 31.9021206,
        'id': 51,
        'facebook': 'https://www.facebook.com/escapezonerehovot/',
        'escapecard': '',
        'company': 'Escape Zone',
        'selected': true,
        'link': 'http://www.escape-zone.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank-2/js79d',
        'review_score': '7.9'
    },
    '111': {
        'address': 'Kibbuz HaGoshrim',
        'favicon': '/static/Logos/northescape.png',
        'roomescape_id': 'carmen-mona-lisa',
        'name': 'Carmen San Diego - The Mona Lisa Mystery',
        'tel': '055-6674537',
        'y': 35.6221615,
        'people': '2-6',
        'trip': '',
        'city': 'Galilee',
        'x': 33.2243683,
        'id': 111,
        'facebook': '',
        'escapecard': '1',
        'company': 'North Escape',
        'selected': true,
        'link': 'http://www.north-escape.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#הזמן-עכשיו',
        'review_score': '-'
    },
    '76': {
        'address': 'Maskit 9',
        'favicon': '',
        'roomescape_id': 'caribbean-pirates-dead-mans-chest',
        'name': 'Pirates Escape',
        'tel': '054-5354827',
        'y': 34.8116132,
        'people': '2-6',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7928499-Reviews-Brainit_Real_Life_Room_Escape_Game-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Herzliya',
        'x': 32.1655795,
        'id': 76,
        'facebook': 'https://www.facebook.com/brainit.co.il',
        'escapecard': '',
        'company': 'Brainit',
        'selected': true,
        'link': 'http://brainit.co.il/f1/room/pirates/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.8'
    },
    '53': {
        'address': 'Altalena 14',
        'favicon': '/static/Logos/sherlocked.png',
        'roomescape_id': 'anthrax',
        'name': 'Anthrax',
        'tel': '03-6523399',
        'y': 34.7629787,
        'people': '2-6',
        'trip': '',
        'city': 'Rishon LeZion',
        'x': 31.99100779999999,
        'id': 53,
        'facebook': 'https://www.facebook.com/SHERLOCKEDISRAEL',
        'escapecard': '1',
        'company': 'Sherlocked',
        'selected': true,
        'link': 'http://sherlocked.co.il/escape_rooms/anthrax/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.1'
    },
    '117': {
        'address': 'Moshe Levi 9',
        'favicon': '/static/Logos/mistory.png',
        'roomescape_id': 'torpedo',
        'name': 'Torpedo',
        'tel': '054-4248855',
        'y': 34.7739996,
        'people': '2-6',
        'trip': '',
        'city': 'Rishon LeZion',
        'x': 31.9888715,
        'id': 117,
        'facebook': 'https://www.facebook.com/MistoryEscapeRooms/',
        'escapecard': '',
        'company': 'Mistory',
        'selected': true,
        'link': 'http://mistory.co.il/%D7%98%D7%95%D7%A8%D7%A4%D7%93%D7%95/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.0'
    },
    '19': {
        'address': 'HaTikshoret 5',
        'favicon': '/static/Logos/exitgame.png',
        'roomescape_id': 'goblet-of-magic',
        'name': 'Goblet of Magic',
        'tel': '058-5595577',
        'y': 34.657145,
        'people': '2-5(x2)',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g1137841-d7751597-Reviews-ExitGame_Israel-Ashdod_Southern_District.html',
        'city': 'Ashdod',
        'x': 31.813712,
        'id': 19,
        'facebook': 'https://www.facebook.com/exitgame1',
        'escapecard': '1',
        'company': 'Exit Game',
        'selected': true,
        'link': 'http://www.exitgame.co.il/he/Games?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.3'
    },
    '119': {
        'address': 'HaShdera HaMerkazit 15',
        'favicon': '/static/Logos/60minutes.png',
        'roomescape_id': '',
        'name': 'Hostage',
        'tel': '050-7130013',
        'y': 34.968473,
        'people': '2-6',
        'trip': '',
        'city': "Modi'in",
        'x': 31.9225937,
        'id': 119,
        'facebook': 'https://www.facebook.com/60Minutes-Escape-Room-Modiin-Hostage-1709054745979074/',
        'escapecard': '',
        'company': '60Minutes',
        'selected': true,
        'link': 'http://www.60minutes.co.il/?page_id=3973&utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '-'
    },
    '97': {
        'address': 'Ha-Yetsira 10',
        'favicon': '',
        'roomescape_id': 'farmer-john',
        'name': 'Farmer John',
        'tel': '09-9552277',
        'y': 34.8769265,
        'people': '2-6',
        'trip': '',
        'city': 'Raanana',
        'x': 32.1950134,
        'id': 97,
        'facebook': 'https://www.facebook.com/getawayisrael/',
        'escapecard': '',
        'company': 'Getaway',
        'selected': true,
        'link': 'http://www.get-away.co.il/Room/8?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.2'
    },
    '34': {
        'address': 'Hahistadrut 19',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'hunting-club',
        'name': 'Hunting Club',
        'tel': '054-6394464',
        'y': 34.7880849,
        'people': '2-5',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Beer Sheva',
        'x': 31.2388211,
        'id': 34,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://exitroom.co.il/rooms/hunting-club?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '8.0'
    },
    '80': {
        'address': "Menorat HaMa'or 3",
        'favicon': '/static/Logos/beithaquest.png',
        'roomescape_id': 'casino-zero',
        'name': 'Casino Zero',
        'tel': '03-5535585',
        'y': 34.7963779,
        'people': '2-6',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0744848,
        'id': 80,
        'facebook': 'https://www.facebook.com/BeitQuest/',
        'escapecard': '',
        'company': 'Beit HaQuest',
        'selected': true,
        'link': 'http://beithaquest.co.il/casino-secret?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '5.0'
    },
    '98': {
        'address': "HaArba'a 4",
        'favicon': '',
        'roomescape_id': 'way-to-hell',
        'name': 'Way to Hell',
        'tel': '052-4104850',
        'y': 34.7830155,
        'people': '2-6',
        'trip': '',
        'city': 'Tel Aviv',
        'x': 32.0703637,
        'id': 98,
        'facebook': 'https://www.facebook.com/Panica-חדרי-בריחה-1554723438171978/',
        'escapecard': '',
        'company': 'Panica',
        'selected': true,
        'link': 'http://panica-escape.co.il/%D7%94%D7%96%D7%9E%D7%A0%D7%AA-%D7%9E%D7%A9%D7%97%D7%A7/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.3'
    },
    '41': {
        'address': 'Eliezer Mazal 5',
        'favicon': '',
        'roomescape_id': 'the-silent-library',
        'name': 'The Silent Library',
        'tel': '058-4130813',
        'y': 34.7711545,
        'people': '2-5',
        'trip': '',
        'city': 'Rishon LeZion',
        'x': 31.9902472,
        'id': 41,
        'facebook': 'https://www.facebook.com/Riddlestorm',
        'escapecard': '',
        'company': 'Riddlestorm',
        'selected': true,
        'link': 'http://riddlestorm.co.il?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.1'
    },
    '30': {
        'address': 'Jabotinsky 79',
        'favicon': '/static/Logos/exitroom.png',
        'roomescape_id': 'black-and-white',
        'name': 'Black & White',
        'tel': '054-2870767',
        'y': 34.8128567,
        'people': '2-4',
        'trip': 'http://www.tripadvisor.com/Attraction_Review-g293984-d7292011-Reviews-Exit_Room-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Ramat Gan',
        'x': 32.0873765,
        'id': 30,
        'facebook': 'https://www.facebook.com/exitroom.israel',
        'escapecard': '',
        'company': 'Exit Room',
        'selected': true,
        'link': 'http://exitroom.co.il/rooms/black-and-white?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '7.9'
    },
    '66': {
        'address': "HaTa'as 24",
        'favicon': '/static/Logos/escapers.png',
        'roomescape_id': 'the-experiment',
        'name': 'The Experiment',
        'tel': '052-5514957',
        'y': 34.9274285,
        'people': '2-5',
        'trip': '',
        'city': 'Kfar Saba',
        'x': 32.1770154,
        'id': 66,
        'facebook': 'https://www.facebook.com/Escapers-761030844023315',
        'escapecard': '',
        'company': 'Escapers',
        'selected': true,
        'link': 'http://www.escapers.co.il/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper#!blank/mainPage',
        'review_score': '7.6'
    },
    '81': {
        'address': "Sha'ar Palmer 1",
        'favicon': '/static/Logos/questplace.png',
        'roomescape_id': '',
        'name': 'The Lost Tomb',
        'tel': '052-6573911',
        'y': 34.999997,
        'people': '2-6',
        'trip': '',
        'city': 'Haifa',
        'x': 32.8197906,
        'id': 81,
        'facebook': 'https://www.facebook.com/QuestPlaceIL',
        'escapecard': '',
        'company': 'Quest Place',
        'selected': true,
        'link': 'http://questplace.co.il/?q=1&utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '-'
    },
    '105': {
        'address': "Sha'ul HaMelech 35",
        'favicon': '/static/Logos/vertigo.png',
        'roomescape_id': 'thebunker',
        'name': 'The Bunker',
        'tel': '03-9600040',
        'y': 34.7898762,
        'people': '2-6',
        'trip': 'https://www.tripadvisor.com/Attraction_Review-g293984-d9594033-Reviews-Vertigo_Escape_Rooms-Tel_Aviv_Tel_Aviv_District.html',
        'city': 'Tel Aviv',
        'x': 32.0773805,
        'id': 105,
        'facebook': 'https://www.facebook.com/vertigotlv/',
        'escapecard': '',
        'company': 'Vertigo',
        'selected': true,
        'link': 'https://vertigotlv.com/booking/?utm_source=escaper.co.il&utm_medium=referral&utm_campaign=escaper',
        'review_score': '9.3'
    }
};
